FROM python:3.11-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir pandas numpy PyYAML pyarrow streamlit plotly

COPY . /app

CMD ["streamlit", "run", "bi_app/streamlit_app.py", "--server.address", "0.0.0.0", "--server.port", "8501"]
