FROM apache/airflow:3.3.1-python3.11

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl git libpq-dev build-essential \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir pandas numpy PyYAML SQLAlchemy psycopg2-binary pydantic requests python-dotenv pyarrow "dbt-core>=1.9,<1.12" "dbt-postgres>=1.9,<1.10" "fastapi>=0.133,<0.134" "starlette>=1.3.1,<1.4" "uvicorn[standard]>=0.37,<0.53" streamlit plotly great_expectations
