select
    cast(event_id as {{ dbt.type_string() }}) as event_id,
    cast(user_pseudo_id as {{ dbt.type_string() }}) as user_pseudo_id,
    cast(session_id as {{ dbt.type_string() }}) as session_id,
    cast(event_timestamp as timestamp) as event_timestamp,
    cast(event_date as date) as event_date,
    lower(cast(event_name as {{ dbt.type_string() }})) as event_name,
    cast(source as {{ dbt.type_string() }}) as source,
    cast(medium as {{ dbt.type_string() }}) as medium,
    cast(campaign as {{ dbt.type_string() }}) as campaign,
    cast(campaign_id as {{ dbt.type_string() }}) as campaign_id,
    cast(landing_page as {{ dbt.type_string() }}) as landing_page,
    lower(cast(device_category as {{ dbt.type_string() }})) as device_category,
    cast(region as {{ dbt.type_string() }}) as region,
    cast(country as {{ dbt.type_string() }}) as country,
    cast(product as {{ dbt.type_string() }}) as product,
    cast(engagement_indicator as integer) as engagement_indicator,
    cast(conversion_indicator as integer) as conversion_indicator,
    cast(revenue as {{ dbt.type_numeric() }}) as revenue,
    cast(attribution_id as {{ dbt.type_string() }}) as attribution_id,
    cast(batch_id as {{ dbt.type_string() }}) as batch_id,
    cast(updated_at as timestamp) as updated_at,
    cast(source_system as {{ dbt.type_string() }}) as source_system
from {{ source('raw', 'ga4_events') }}
