-- Business question: What is the executive campaign ROI scorecard?
-- Assumptions:
--   1. Inputs are synthetic CSV exports generated by the local demo/evidence path.
--   2. Metrics support local review and analyst investigation; budget automation is a deployment extension.
-- Output purpose: Use as a board-level starting point for spend, revenue, ROAS, CAC, and volume review.
-- Dialect: DuckDB. This query reads the generated BI export CSV for reproducible local review.

with base as (
    select *
    from read_csv_auto('data/exports/demo_mart_channel_performance.csv', header=true)
),
ranked as (
    select
        *,
        row_number() over () as output_rank
    from base
)
select *
from ranked
limit 100;
