-- Business question: Which campaign actions should be prioritized?
-- Assumptions:
--   1. Inputs are synthetic CSV exports generated by the local demo/evidence path.
--   2. Metrics support local review and analyst investigation; budget automation is a deployment extension.
-- Output purpose: Review deterministic scale, pause, reallocate, funnel, attribution, and quality actions.
-- Dialect: DuckDB. This query reads the generated BI export CSV for reproducible local review.

with base as (
    select *
    from read_csv_auto('data/exports/analyst_outputs/campaign_action_recommendations.csv', header=true)
),
ranked as (
    select
        *,
        row_number() over () as output_rank
    from base
)
select *
from ranked
limit 100;
